### ISSUE TITLE
Need help with PMIX_SERVER_URI and tool

### ISSUE THREAD

**Issue by angainor** [pmix/pmix#907]
I am running pmix-3.0.2, either with prrte, or with ompi v4.0.x. In one scenario I start the `prte` server as a `-system-server`. I then `prun` a client, which queries and prints the `PMIX_SERVER_URI`:

```
$prun -np 1 ./mclient
Client ns 424411138 rank 0: Running
Client 424411138:0 universe size 64
Client 424411138:0 num procs 1
query info entries 1
key: pmix.srvr.uri value: 424411136.0;tcp://10.1.1.121,169.254.95.120,10.3.1.121,10.4.1.121:56578
```

I would assume that I can take this URI and plug it into `PMIx_tool_init`, but it doesn't work. If I use the above, my simple tool complains:

```
$ ./tool "424411136.0;tcp://10.1.1.121,169.254.95.120,10.3.1.121,10.4.1.121:56578"
contacting server at 424411136.0;tcp://10.1.1.121,169.254.95.120,10.3.1.121,10.4.1.121:56578
[c11-5.cluster:28102] ptl_tcp_parse_uri: Could not convert 0.1.1.121,169.254.95.120,10.3.1.121,10.4.1.121
[c11-5.cluster:28102] PMIX ERROR: BAD-PARAM in file ptl_tcp.c at line 758
PMIx_tool_init failed: -25
```
So there are some URI parsing problems. If I use a simple TCP uri, then I get an unreachable error:

```
$ ./tool "tcp://127.0.0.1:56578"
contacting server at tcp://127.0.0.1:56578
PMIx_tool_init failed: -25
```

Note that I simply run the `tool` from the command line, without any `prun`, but I think that's how it should be? Am I doing something wrong?

**Comment by angainor** [comment]
Here is the tool init code:

```
        PMIX_INFO_CREATE(info, 1);                                                                                                                                                                                                                                                 
        uri = strdup(argv[1]);                                                                                                                                                                                                                                                     
        fprintf(stderr, "contacting server at %s\n", uri);                                                                                                                                                                                                                         
        PMIX_INFO_LOAD(info, PMIX_SERVER_URI, uri, PMIX_STRING);                                                                                                                                                                                                                   
        if (PMIX_SUCCESS != (rc = PMIx_tool_init(&myproc, info, 1))) {                                                                                                                                                                                                             
            fprintf(stderr, "PMIx_tool_init failed: %d\n", rc);                                                                                                                                                                                                                    
            exit(rc);                                                                                                                                                                                                                                                              
        }                                                                                                                                                                                                                                                                          
        PMIX_INFO_FREE(info, 1);                                                                                                                                                                                                                                                   
```

**Comment by rhc54** [comment]
I'm a little under the weather and not available much, I fear. Will try to help when better, hopefully towards end of next week. However, your URI is definitely not correct as the "tcp" portion must indicate IPv4/6 - i.e., it should be "tcp4" or "tcp6". How did you retrieve it?

**Comment by angainor** [comment]
@rhc54 No rush, it's nothing that can't wait. I might have been a bit optimistic here :) I'm reading the code, in particular `orte/orted/pmix/pmix_server_gen.c`, in which I saw that I can query for `PMIX_SERVER_URI`. So I did that in the client:

```
        /* query the uri */
        pmix_query_t *query;
        int nq = 1;
        PMIX_QUERY_CREATE(query, nq);
        query[0].keys = (char**)malloc(2 * sizeof(char*));
        query[0].keys[0] = strdup(PMIX_SERVER_URI);
        query[0].keys[1] = NULL;
        active = true;
        if (PMIX_SUCCESS != (rc = PMIx_Query_info_nb(query, nq, query_cb, (void*)&active))) {
            fprintf(stderr, "Client ns %s rank %d: PMIx_Query_info failed: %d\n", myproc.nspace, myproc.rank, rc);
            goto done;
        }
```
And this is what I got:

```
key: pmix.srvr.uri 
value: 424411136.0;tcp://10.1.1.121,169.254.95.120,10.3.1.121,10.4.1.121:56578
```
I assumed that I can simply plug this into the `PMIX_SERVER_URI` argument of the tool init function. But this query is not documented in the pmix standard, so I guess I was too optimistic? How else can I obtain the correct URI?

Thanks!

**Comment by rhc54** [comment]
That’s correct so it sounds like a bug in the stored value

**Comment by rhc54** [comment]
Actually, I take that back - turns out that this is a "bug" in PRRTE. When you perform the query, it gets sent to the PRRTE daemon for processing - the PMIx server passes it up to the host daemon. In that code, we see this:
```c
PMIX_INFO_LOAD(kv->info, PMIX_SERVER_URI, orte_process_info.my_hnp_uri, PMIX_STRING);
```
In other words, PRRTE is returning the URI of the out-of-band connection used between PRRTE daemons, and _not_ the URI of the PMIx server library itself.

What we have here is a little confusion as there are multiple URI's in operation. I think the ```PMIX_SERVER_URI``` attribute should definitely refer to the PMIx server library's connection. We probably then need to add something like ```PMIX_HOST_URI``` to access any URI value for the host daemon's network connections.

Adding an attribute will have to wait for the next standard's release. However, I think it is reasonable that we clarify the current attribute, and have the server library look for it and return the expected value.

**Comment by rhc54** [comment]
Figured out a way to provide the non-PMIx URI within the current definitions by using the ```PMIX_PROC_URI``` attribute, clarifying that this will return any non-PMIx URI of a given process. Since a client process cannot directly connect to another client process, this attribute can only refer to a non-PMIx connection point. PMIx connection points for a server can be obtained via the ```PMIX_SERVER_URI``` attribute.

Will try to have this implemented this week and scheduled for release in the v2.2 and v3.1 series.

**Comment by angainor** [comment]
@rhc54 I checked and the same (or similar) value is returned in the OpenMPI environment (i.e., `mpirun`):

```
$ mpirun -np 2 -H c11-3,c11-5 ./mclient
Client ns 3527081985 rank 1: Running
Client 3527081985:1 universe size 2
Client 3527081985:1 num procs 2
Client ns 3527081985 rank 0: Running
Client 3527081985:0 universe size 2
Client 3527081985:0 num procs 2
query info entries 1
key: pmix.srvr.uri value: 3527081984.0;tcp://10.1.1.121,169.254.95.120,10.3.1.121,10.4.1.121:49622
query info entries 1
key: pmix.srvr.uri value: 3527081984.0;tcp://10.1.1.121,169.254.95.120,10.3.1.121,10.4.1.121:49622
```

So I guess this should also be changed in ORTE / OPAL?

**Comment by angainor** [comment]
@rhc54 btw. In the above run with 2 ranks, each rank is started on a different node. I guess each rank will report it's local PMIx server address? unlike what they report now, which is the same address of some host server (`mpirun` ?).

**Comment by rhc54** [comment]
If you take the ```PMIX_SERVER_URI3``` envar value and pass it in as ```PMIX_SERVER_URI```, it should work (I believe).

ORTE will need to be updated - OPAL will track the PMIx release.

**Comment by angainor** [comment]
@rhc54 `PMIX_SERVER_URI3` doesn't work, unfortunately. First, it is the local IP loopback address only. Here I print the `getenv` value from a client:

```
mpirun -np 1 -H c11-5:32 ./mclient
PMIX_SERVER_URI3 2716401664.0;tcp4://127.0.0.1:22688
```

Even if I run my tool from the same host, I can't connect. Using the entire address:

```
./tool "2716401664.0;tcp4://127.0.0.1:22688"
contacting server at 2716401664.0;tcp4://127.0.0.1:22688
[c11-5.cluster:124293] PMIX ERROR: NOT-SUPPORTED in file ptl_tcp.c at line 1058
[c11-5.cluster:124293] PMIX ERROR: NOT-SUPPORTED in file ptl_tcp.c at line 790
PMIx_tool_init failed: -25
```

and using only the part starting with tcp4:

```
./tool "tcp4://127.0.0.1:22688"
contacting server at tcp4://127.0.0.1:22688
PMIx_tool_init failed: -25
```

**Comment by angainor** [comment]
@rhc54 Well, my MPI jobs are still running at the time I try to connect to them. That is, the ranks are in a `while(true);` loop. The idea was to inspect a running job from the side, e.g., to obtain information about it's progress, or to trigger some events (checkpoint) using a PMIx tool. Will that work?

**Comment by rhc54** [comment]
Yes, it should, though that is also true with PRRTE (just start your job with prun). It's what I'm doing now during development of the debugger support. I'll have to poke at it a bit to see why you're hitting problems.

Out of curiosity: if you just let the tool "discover" the local PMIx server (i.e., don't try to provide a server URI), does it work for you? Also, have you tried this with head of PMIx and PRRTE master branches (this is where I am working)?

**Comment by rhc54** [comment]
FWIW: the combination of PRRTE and PMIx masters works fine. I was able to print the value of  ```PMIX_SERVER_URI3``` and pass it to a tool app that included it as ```PMIX_SERVER_URI``` to the tool_init function, and things connected as they should. So the problem is likely either something in PMIx v3.0.2 or in OMPI.

**Comment by angainor** [comment]
@rhc54 Thanks! 

I managed to make two scenarios work with PRRTE. First, the tool initializes correctly if I don't pass anything (but this would only work with PRRTE, not OpenMPI, right?). Second, I started the `prte` on master node, then I started the client, which printed the `PMIX_SERVER_URI3`. When I used that initialize the tool (also running tool on the same node), it made the connection.

The scenario that didn't work was when I ran `prte -H c11-3 -d` on the master node `c11-5`. Then, on the master node (`c11-5`) I used `prun -np 1 ./mclient` to start the client. In this case the value of `PMIX_SERVER_URI3` that client printed was unusable on both the master, and the compute node. It looks to me that it should work on the master node (`c11-5`), because I get fewer error messages there:

```
[marcink@c11-5 examples]$ ./tool "2358968320.1;tcp4://127.0.0.1:1332"
contacting server at 2358968320.1;tcp4://127.0.0.1:1332
PMIx_tool_init failed: -25
```

vs. compute node

```
[marcink@c11-3 examples]$ ./tool "2358968320.1;tcp4://127.0.0.1:1332"
contacting server at 2358968320.1;tcp4://127.0.0.1:1332
[c11-3.cluster:55543] PMIX ERROR: NOT-SUPPORTED in file ptl_tcp.c at line 1058
[c11-3.cluster:55543] PMIX ERROR: NOT-SUPPORTED in file ptl_tcp.c at line 790
PMIx_tool_init failed: -25
```

**Comment by rhc54** [comment]
Okay, I'm still not 100% and so am working a little slower. Agreed that my test was done on a single node.

Let me first address the initial problem of the query so that doesn't get lost. Then I'll circle back to the multi-node tool support. In your example, I suspect the mclient was running on the compute node, and so the URI3 would be for that daemon. However, if your tool was run on that node, then I'm surprised that wouldn't work.

Just to check, however: did you run that test with PMIx master? Or with v3.0.2? Again, I am beginning to suspect there is something missing in the latter.

**Comment by angainor** [comment]
@rhc54 I have checked now with PMIx-master and PRRTE-master, and the behavior is the same: if I start `prte` and the client on a remote host, then my tool cannot connect to the server address reported in the client's `PMIX_SERVER_URI3` variable. I am running the tool on the remote host, where the client runs.

As before, running the tool without specifying the `PMIX_SERVER_URI` key works on the master node.

**Comment by rhc54** [comment]
I finally tracked this down. The issue was that I hadn't implemented (in PRRTE) the ability for a tool to connect to a PMIx server on a backend node - i.e., a tool running on a remote host that has a prte daemon (but not prte itself) running on it. This has now been fixed.

I also fixed the query so that you can, if you wish, just use PMIx_Get with the ```PMIX_SERVER_URI``` key to retrieve the server's PMIx connection point. You can get the non-PMIx URI of the server by querying with the ```PMIX_PROC_URI``` key.

HTH
Ralph

**Comment by angainor** [comment]
@rhc54 Thanks, Ralph! I'll get back to this as soon as I can, and let you know how this goes. We are having a pretty busy pre-Chrismass season here, so it might take me a while. Thanks again!

**Comment by angainor** [comment]
@rhc54 Hi, Ralph - and Happy New Year! I've tried the newest PMIx master and PRRTE master again. Some progress, but I still have trouble - might be because I'm doing things wrong.

I started `prte` on 4 compute nodes (`/prte -H c11-1:1,c11-2:1,c11-3:1,c11-4:1 -d`). Then, I ran my client program, which obtains the `PMIX_SERVER_URI` key and displays it:
```
prun -np 4 ./mclient
PMIX_SERVER_URI3 649068544.2;tcp4://127.0.0.1:46542
PMIX_SERVER_URI3 649068544.3;tcp4://127.0.0.1:50150
PMIX_SERVER_URI3 649068544.1;tcp4://127.0.0.1:49269
PMIX_SERVER_URI3 649068544.0;tcp4://10.1.1.120:51452
rank 0: key: pmix.srvr.uri rank 0: value: 649068544.0;tcp4://10.1.1.120:51452
rank 1: key: pmix.srvr.uri rank 1: value: 649068544.1;tcp4://127.0.0.1:49269
rank 2: key: pmix.srvr.uri rank 2: value: 649068544.2;tcp4://127.0.0.1:46542
rank 3: key: pmix.srvr.uri rank 3: value: 649068544.3;tcp4://127.0.0.1:50150
```
So first observation is that only one rank displays a world-accessible server URI. When I use that URI to connect my tool, it works fine. However, if I start my client on a subset of nodes that do not include the node that I used to start `prte`, then I only get the loopback device address, and can't connect remotely:
```
prun -np 1 -H c11-1 ./mclient
PMIX_SERVER_URI3 791412736.1;tcp4://127.0.0.1:2136
rank 0: key: pmix.srvr.uri rank 0: value: 791412736.1;tcp4://127.0.0.1:2136
```
Anyway, then I try to obtain some information about "client" job from within the "tool" job, and this is where I have problems. Looking at the newest PMIx standard document on `PMIx_Query_info_nb`, there seem to be 2 sections about "Required attributes", which are not the same. It seems that the first one is old/obsolete (?), because I cannot find any of the `PMIX_*_INFO` tags in the sources. But there is the `PMIX_NSPACE` attribute, so I figured I need to add this to my query in order to get what I want. So, in the tool I try to ask about the "client" job size as follows:

```
        nq = 1;                                                                                                                          
        PMIX_QUERY_CREATE(query, nq);                                                                                                    
        query[0].keys = (char**)malloc( 2* sizeof(char*));                                                                               
        query[0].keys[0] = strdup(PMIX_JOB_SIZE);                                                                                        
        query[0].keys[1] = NULL;                                                                                                         
                                                                                                                                         
        PMIX_INFO_CREATE(query[0].qualifiers, 1);                                                                                        
        PMIX_INFO_LOAD(query[0].qualifiers, PMIX_NSPACE, namespace, PMIX_STRING);                                                        
                                                                                                                                         
        active = true;                                                                                                                   
        if (PMIX_SUCCESS != (rc = PMIx_Query_info_nb(query, nq, cbfunc, (void*)&active))) {                                              
            fprintf(stderr, "Client ns %s rank %d: PMIx_Query_info failed: %d\n", myproc.nspace, myproc.rank, rc);                       
            goto done;                                                                                                                   
        }                                                                                                                                
        while(active) {                                                                                                                  
            usleep(10);                                                                                                                  
        }                                                                                                                                
        PMIX_QUERY_FREE(query, nq);                                                                                                      
```
where `namespace` is the namespace of the client (`649068544` for the first example above). In return I get 1, which - I'm guessing - is the value for the tool namespace, and not the client namespace, which should be 4.

Clearly I must be doing something wrong. I used the `qualifiers` field based on the code I found in `examples/debugger.c:attach_to_running_job`, but that one is probably old, since it is `#if 0` - inactive.

Finally a possible small bug: the `tool.c` example I used as a base ends with a call to `PMIx_Finalize(NULL, 0);`. Should it not end with `PMIx_tool_finalize();`? Then when I run my tool it hangs inside `PMIx_tool_finalize();`.

Do you have any suggestions?

**Comment by angainor** [comment]
@rhc54 Another thing related to the last mentioned problem is that when the tool hangs in `PMIx_tool_finalize` and I press Ctrl-C, then the server doesn't ever notice that the tool is no longer active. Consequently, the namespace created for the tool remains forever on the server list of namespaces (I check using `PMIX_QUERY_NAMESPACES`).

**Comment by angainor** [comment]
@rhc54 I've figured at least part of the problem: the namespace qualifier I added was not recognized, because I did not set `query[0].nqual=1`. That is not a very obvious thing to do, e.g., `example/alloc.c` doesn't do it, so it is likely wrong also. When I did that, `PMIx_tool_finalize` doesn't hang anymore, but I also don't get any entries in my query. Is it allowed to ask for `PMIX_JOB_SIZE` in this context?

**Comment by rhc54** [comment]
> rank 0: key: pmix.srvr.uri rank 0: value: 649068544.0;tcp4://10.1.1.120:51452
rank 1: key: pmix.srvr.uri rank 1: value: 649068544.1;tcp4://127.0.0.1:49269
rank 2: key: pmix.srvr.uri rank 2: value: 649068544.2;tcp4://127.0.0.1:46542
rank 3: key: pmix.srvr.uri rank 3: value: 649068544.3;tcp4://127.0.0.1:50150
So first observation is that only one rank displays a world-accessible server URI. When I use that URI to connect my tool, it works fine. However, if I start my client on a subset of nodes that do not include the node that I used to start prte, then I only get the loopback device address, and can't connect remotely:

Yes, that is a PRRTE setting - it only was set to allow remote connections from the master node (i.e., where ```prte``` itself is running). It's always a debate about allowing TCP connections directly from a login node to a compute node, but I see no real harm in changing the PRRTE setting - if the cluster doesn't allow such connections, it can simply block them.

Please see https://github.com/pmix/prrte/pull/186

**Comment by rhc54** [comment]
> Looking at the newest PMIx standard document on PMIx_Query_info_nb, there seem to be 2 sections about "Required attributes", which are not the same. It seems that the first one is old/obsolete (?), because I cannot find any of the PMIX_*_INFO tags in the sources.

The first section states it is for ```PMIx libraries```, while the second section states it is for ```Host environments```. I believe we have begun to combine the two and just let the wordings divide them.

The ```PMIX_*_INFO``` keys listed there do exist - they just haven't been implemented yet. I'm still working on bringing the library into full compliance with the standard, which is why v3.1.0 has not yet been released 😄

**Comment by rhc54** [comment]
> I've figured at least part of the problem: the namespace qualifier I added was not recognized, because I did not set query[0].nqual=1. That is not a very obvious thing to do, e.g., example/alloc.c doesn't do it, so it is likely wrong also.

I'll address the example (hasn't been touched in a long time). I'm not sure how to make it more obvious that you need to set the number of elements in the array you are passing us. Any suggestions?

> When I did that, PMIx_tool_finalize doesn't hang anymore, but I also don't get any entries in my query. Is it allowed to ask for PMIX_JOB_SIZE in this context?

Yes, but PRRTE likely hasn't implemented it yet. However, I think I might add something to the PMIx server to check for such info before passing the request up to the host, just to make implementation easier for host environments. Writing code to check for every possible request/qualifier combination can be tedious. I'll see what I can do to make it easier on them.

**Comment by rhc54** [comment]
> Another thing related to the last mentioned problem is that when the tool hangs in PMIx_tool_finalize and I press Ctrl-C, then the server doesn't ever notice that the tool is no longer active. Consequently, the namespace created for the tool remains forever on the server list of namespaces (I check using PMIX_QUERY_NAMESPACES).

Hmmm...that shouldn't happen. I'll take a look - thx!

**Comment by rhc54** [comment]
> > Another thing related to the last mentioned problem is that when the tool hangs in PMIx_tool_finalize and I press Ctrl-C, then the server doesn't ever notice that the tool is no longer active. Consequently, the namespace created for the tool remains forever on the server list of namespaces (I check using PMIX_QUERY_NAMESPACES).
> 
> Hmmm...that shouldn't happen. I'll take a look - thx!

Okay, I think I have this fixed by a combination of https://github.com/pmix/pmix/pull/1022 and https://github.com/pmix/prrte/pull/187. I also fixed the case where prun would hang if the job failed to launch for some reason.

**Comment by rhc54** [comment]
I believe I have now addressed the concerns about the examples being out-of-date and implemented the server checking its cache for queried info before asking the host. This should let you find the PMIX_JOB_SIZE for your child job.

Last thing I plan to do is implement a simpler way for you to query the server URI of a remote PMIx server. You probably already realized that you can use PMIx_Get with PMIX_SERVER_URI to retrieve the URI of your local server, and that PMIX_PROC_URI would return the out-of-band inter-daemon connection info (if the RM is willing to expose it). I'll implement a PMIx_Query method by which you can pass the name of the node as a qualifier and ask for PMIX_SERVER_URI to get the connection point for a remote tool.

Hope this all helps! I do appreciate your trying things as it has helped to expose some gaps...and is providing me with input I'm using in the new "tools" chapter of the upcoming PMIx 4 standard!

**Comment by angainor** [comment]
> Yes, that is a PRRTE setting - it only was set to allow remote connections from the master node (i.e., where `prte` itself is running). It's always a debate about allowing TCP connections directly from a login node to a compute node, but I see no real harm in changing the PRRTE setting - if the cluster doesn't allow such connections, it can simply block them.
> 
> Please see [pmix/prrte#186](https://github.com/pmix/prrte/pull/186)

This worked! I guess integration into OpenMPI and/or SLURM is a different topic, but at least when you use `mpirun` then it seems to me that the main node would be one of the assigned compute nodes anyway. So you might as well provide address to all servers. Anyway, this worked :)

**Comment by angainor** [comment]
@rhc54 
> I'll address the example (hasn't been touched in a long time). I'm not sure how to make it more obvious that you need to set the number of elements in the array you are passing us. Any suggestions?

Well, the best would of course be if one wouldn't have to do it at all. I do provide this information already when creating the qualifiers list, so explicitly setting `nqual` is a bit excessive:
```
        PMIX_INFO_CREATE(query[0].qualifiers, 1);                                                                                                                                                                                                                                  
        query[0].nqual = 1;                                                                                                                                                                                                                                                        
        PMIX_INFO_LOAD(&query[0].qualifiers[0], PMIX_NSPACE, namespace, PMIX_STRING);                                                                                                                                                                                              
```
One way would be to hold the size info in the `pmix_info_t` list, but it seems it's a lot of work. Unless you would allocate `n+1` entries and mark the last one as end of list. You could then extract the length information. Another way would be to add a separate macro, e.g., `PMIX_QUERY_QUAN_CREATE`), which would update the `nqual` field.

**Comment by angainor** [comment]
> I believe I have now addressed the concerns about the examples being out-of-date and implemented the server checking its cache for queried info before asking the host. This should let you find the PMIX_JOB_SIZE for your child job.

Still having problems here - the `PMIX_JOB_SIZE` is not returned, and `prte` server prints the following message when I run my tool:
```
[login-1-2:188724] [[16389,0],0] Releasing job data for [16389,6]
Query for unrecognized attirbute: pmix.job.size
[c11-2.cluster:144562] sess_dir_finalize: proc session dir does not exist
[c11-2.cluster:144562] sess_dir_finalize: job session dir does not exist
[c11-2.cluster:144562] sess_dir_finalize: jobfam session dir not empty - leaving
[c11-2.cluster:144562] sess_dir_finalize: jobfam session dir not empty - leaving
[c11-2.cluster:144562] sess_dir_finalize: top session dir not empty - leaving
```
So somehow job size is still not recognized when I provide the `PMIX_NSPACE` qualifier. It's fine without it, of course. 

The left-over namespaces are also still there. Each time I run the tool, namespace info is created on the PMIx server I connect to. Maybe the above warnings are relevant?

> Last thing I plan to do is implement a simpler way for you to query the server URI of a remote PMIx server. You probably already realized that you can use PMIx_Get with PMIX_SERVER_URI to retrieve the URI of your local server, and that PMIX_PROC_URI would return the out-of-band inter-daemon connection info (if the RM is willing to expose it). I'll implement a PMIx_Query method by which you can pass the name of the node as a qualifier and ask for PMIX_SERVER_URI to get the connection point for a remote tool.

Oh that would be cool! You will then be able to inspect jobs without any help from their side, or anybody else's. Just to find possible problems ;) What if there is more than one PMIx server running on a node? (e.g., multiple MPI Jobs). I guess some more qualifiers are needed to distinguish?

> Hope this all helps! I do appreciate your trying things as it has helped to expose some gaps...and is providing me with input I'm using in the new "tools" chapter of the upcoming PMIx 4 standard!

I'm also happy I can help. I'm looking into this mostly because of the event infrastructure (as we discussed in #807). But the tool capabilities seem really useful for general-purpose job inspection capabilities!

**Comment by angainor** [comment]
> Yes, but PRRTE likely hasn't implemented it yet. However, I think I might add something to the PMIx server to check for such info before passing the request up to the host, just to make implementation easier for host environments. Writing code to check for every possible request/qualifier combination can be tedious. I'll see what I can do to make it easier on them.

A general node. It would be useful to have some server / RM capabilities query method. Since most keys / attributes are not obligatory, it would make users' life easier to ask for what can be used. Or is there such an interface already?

**Comment by rhc54** [comment]
> One way would be to hold the size info in the pmix_info_t list, but it seems it's a lot of work. Unless you would allocate n+1 entries and mark the last one as end of list. You could then extract the length information. Another way would be to add a separate macro, e.g., PMIX_QUERY_QUANT_CREATE), which would update the nqual field.

I might be able to do something along these lines - let me play a bit with it. Thanks for the suggestions!

**Comment by rhc54** [comment]
> So somehow job size is still not recognized when I provide the PMIX_NSPACE qualifier.

I got the PMIX_JOB_SIZE query working now - take a look at the PRRTE examples/tool.c code to see how it all works now. It also prints out a nice "ps-like" report on what is running.

> The left-over namespaces are also still there. Each time I run the tool, namespace info is created on the PMIx server I connect to. 

I checked the namespaces using that example tool and I can't replicate. Please give it a try and see if you still see the same problem. You'll need to update both PMIx and PRRTE masters - be sure that PRRTE is building against the updated PMIx master.

**Comment by angainor** [comment]
@rhc54 Great, all works now! And I don't see the nspace buildup anymore. Actually, now the tool namespace is not mentioned on the list of namespaces at all, and all I see when I provide a server URI is the client namespace.

Just as a curiosity, I found one 'hidden' namespace, which can be queried, but is not listed by `pmix.qry.ns`. I start the client:
```
prun -np 4 ./mclient
Client ns 3064528899 rank 0: Running
Client ns 3064528899 rank 2: Running
Client ns 3064528899 rank 1: Running
Client ns 3064528899 rank 3: Running
rank 0: key: pmix.srvr.uri rank 0: value: 3064528896.1;tcp4://10.1.1.117:50010
rank 1: key: pmix.srvr.uri rank 1: value: 3064528896.2;tcp4://10.1.1.118:18153
rank 2: key: pmix.srvr.uri rank 2: value: 3064528896.3;tcp4://10.1.1.119:61311
rank 3: key: pmix.srvr.uri rank 3: value: 3064528896.4;tcp4://10.1.1.120:19769
```
The client namespace is `3064528899`, but there is an extra URI prefix namespace `3064528896`, which. It is not listed by the tool:
```
./tool
ACTIVE NSPACES:
	3064528898	prun
	3064528899	./mclient
```
but it can be queried:
```
./tool -nspace 3064528896
JOB SIZE FOR NSPACE 3064528896: 5
```
I guess this is the `prte` session (4 nodes + the head `prte` startup node), which you choose not to show?

Anyways, all works now :)

**Comment by rhc54** [comment]
> I guess this is the prte session (4 nodes + the head prte startup node), which you choose not to show?

Yes - I don't show tools that are not launchers as you cannot connect to them plus the underlying base DVM. I suppose that latter should be shown as it is "attachable" - easy enough to do.

I'll get the extensions we discussed done soon, hopefully today or at latest tomorrow.

**Comment by rhc54** [comment]
Okay, I added the prte job itself to the report: https://github.com/pmix/prrte/pull/192

**Comment by rhc54** [comment]
@angainor I have made progress and/or completed almost all the items discussed on this ticket.

> Oh that would be cool! You will then be able to inspect jobs without any help from their side, or anybody else's. Just to find possible problems ;) What if there is more than one PMIx server running on a node? (e.g., multiple MPI Jobs). I guess some more qualifiers are needed to distinguish?

You can now get the PMIX_SERVER_URI for any PRRTE daemon by simply doing a PMIx query for that attribute, passing a qualifier of the hostname. I haven't quite figured out how we would deal with multiple PRRTE daemons on a node - they won't know about each other, though we could search the rendezvous directories to find them. I'll log that for the future as I'm not sure of the use-case for it. For now, you can get the uri for any node within "range" of the server to which your tool connected.

The example tool has been updated to illustrate usage.

> One way would be to hold the size info in the pmix_info_t list, but it seems it's a lot of work. Unless you would allocate n+1 entries and mark the last one as end of list. You could then extract the length information. Another way would be to add a separate macro, e.g., PMIX_QUERY_QUANT_CREATE), which would update the nqual field.

I actually resolved this in two ways. First, I provided macros for specifically creating query qualifiers and app directives - these fill in the size fields for you. However, since there may already be codes out there that have the issue you cited, I also used the "directives" flag field in the pmix_info_t to "mark" the last one in an array created by PMIX_INFO_CREATE. I haven't updated the APIs yet to check for a zero "size" field and auto-update it, but will do so soon. So either way, we should get the field set.

> A general note. It would be useful to have some server / RM capabilities query method. Since most keys / attributes are not obligatory, it would make users' life easier to be able to ask for what can be used. Or is there such an interface already?

We use the query interface for this now - you can get spawn and debugger support that way. I have an idea on how to generalize that request, but it will have to be in v4 of the Standard as it requires a new API to get the host environment's supported attribute list. I'll put something together and flag you on it for your comments.

**Comment by rhc54** [comment]
> However, since there may already be codes out there that have the issue you cited, I also used the "directives" flag field in the pmix_info_t to "mark" the last one in an array created by PMIX_INFO_CREATE. I haven't updated the APIs yet to check for a zero "size" field and auto-update it, but will do so soon. 

Completed!

**Comment by angainor** [comment]
@rhc54 Thanks Ralph! I'm a bit busy now, so it will take me a while to get through this. But one thing I looked is not clear to me. You said

> You can now get the PMIX_SERVER_URI for any PRRTE daemon by simply doing a PMIx query for that attribute, passing a qualifier of the hostname.

But looking quickly at the `tool.c` example and the `if (geturi) {...}` section I don't see the hostname being used anywhere. So the `--uri` command line argument seems unused.

I'll play around a bit more probably end of this week.

**Comment by rhc54** [comment]
😆 wow - I shutdown the VM before committing the changes! Old man's brain is truly fried. I'll update immediately. Thanks for pointing it out!

**Comment by angainor** [comment]
@rhc54 I finally went through the last changes, and the updated examples, and all works fine on master now :) great!

**Comment by rhc54** [comment]
Excellent! I'm going to go ahead and close this now. I am almost done with the last thing you requested, a method by which you can learn what attributes are supported, and should be committing it soon (hopefully late today).
